### ISSUE TITLE
Error inflating class

### ISSUE THREAD

**Issue by thompsch** [akapelrud/Rotary-Seekbar#17]
Added the repo to gradle and the implementation as `implementation 'com.github.akapelrud:Rotary-Seekbar:v1.0.0'`. Copy-pasted any one of the 16 controls from your example XML and on build I get :

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ca13b.blackdroid/com.ca13b.blackdroid.MainActivity}: android.view.InflateException: Binary XML file line #13: Binary XML file line #13: Error inflating class no.kapelrud.RotarySeekbar
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: android.view.InflateException: Binary XML file line #13: Binary XML file line #13: Error inflating class no.kapelrud.RotarySeekbar
     Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class no.kapelrud.RotarySeekbar
     Caused by: java.lang.reflect.InvocationTargetException
```

SDK: 29

**Comment by akapelrud** [comment]
The only thing I can think of off the top of my head is that you might have forgotten to declare the namespace `app`. In the example `activity_main.xml` there is line no. 3, in the declaration of the container:
```
xmlns:app="http://schemas.android.com/apk/res-auto"
```

There is bound to be errors/bugs in my code, and the documentation leaves something to be desired as of today, so thanks for the heads up.

**Comment by akapelrud** [comment]
I was writing a new app myself, and I got the exact same error. Looking at the whole error output in android studio, it seems that the error originated when trying to access the attribute `colorPrimaryVariant`, which I had not declared in the new app's `style.xml`. After adding:

```
<item name="colorPrimaryVariant">@color/colorPrimaryVariant</item>
```
and declaring the corresponding color in `colors.xml`, the error disappeared.

I hope this helps.
